package me.kvdpxne.covilo.infrastructure.jdbc

// table names
const val TABLE_COMMENT = "comment"
const val TABLE_COMMENT_REACTION = "comment_reaction"
const val TABLE_CRIME = "crime"
const val TABLE_CRIME_CLASSIFICATION = "crime_classification"
const val TABLE_CRIME_PERPETRATOR = "crime_perpetrator"
const val TABLE_LOCATION_CITY = "location_city"
const val TABLE_LOCATION_REGION = "location_region"
const val TABLE_LOCATION_COUNTRY = "location_country"
const val TABLE_USER = "user"

// column names
const val COLUMN_IDENTIFIER = "identifier"
const val COLUMN_KEY = "key"
const val COLUMN_POPULATION = "population"
const val COLUMN_CAPITAL = "capital"
const val COLUMN_DOMESTIC_NAME = "domestic_name"
const val COLUMN_DATE = "date"
const val COLUMN_EMOJI = "emoji"
const val COLUMN_EMAIL = "email"
const val COLUMN_PASSWORD = "password"
const val COLUMN_BIRTH_DATE = "birth_date"
const val COLUMN_CREATED_DATE = "created_date"
const val COLUMN_LAST_MODIFIED_DATE = "last_modified_date"
const val COLUMN_DESCRIPTION = "description"
const val COLUMN_FIRST_NAME = "first_name"
const val COLUMN_LAST_NAME = "last_name"
const val COLUMN_AGE = "age"
const val COLUMN_IS_CAUGHT = "is_caught"
const val COLUMN_IS_CONFIRMED = "is_confirmed"

// foreign key column names
const val COLUMN_CRIME = "crime"
const val COLUMN_CLASSIFICATION = "classification"
const val COLUMN_PERPETRATOR = "perpetrator"
const val COLUMN_CITY = "city"
const val COLUMN_REGION = "region"
const val COLUMN_COUNTRY = "country"
