[versions]
spring-boot = "3.1.0"
spring-management = "1.1.0"
mariadb-client = "3.0.8"
swagger = "3.0.0"
auth0-jwt = "4.1.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-management = { id = "io.spring.dependency-management", version.ref = "spring-management" }

[libraries]
auth0-jwt = { module = "com.auth0:java-jwt", version.ref = "auth0-jwt" }
mariadb-client = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb-client" }
swagger = { module = "io.springfox:springfox-boot-starter", version.ref = "swagger" }
