[versions]
spring-boot = "3.1.1"
spring-management = "1.1.0"
openapi = "2.1.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-management = { id = "io.spring.dependency-management", version.ref = "spring-management" }

[libraries]
openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "openapi" }
