export enum Continent {
  ASIA = "ASIA",
  AFRICA = "AFRICA",
  NORTH_AMERICA = "NORTH_AMERICA",
  SOUTH_AMERICA = "SOUTH_AMERICA",
  ANTARCTICA = "ANTARCTICA",
  EUROPE = "EUROPE",
  OCEANIA = "OCEANIA"
}
