package me.kvdpxne.covilo

const val CRIME_CLASSIFICATION_TABLE  = "crime_classification"
const val CRIME_PERPETRATOR_TABLE     = "crime_perpetrator"
const val CRIME_TABLE                 = "crime"
const val LOCATION_CITY_TABLE         = "location_city"
const val LOCATION_COUNTRY_TABLE      = "location_country"
const val LOCATION_REGION_TABLE       = "location_region"
const val USER_TABLE                  = "user"

const val AGE_COLUMN                  = "age"
const val CAPITAL_COLUMN              = "capital"
const val CAUGHT_COLUMN               = "caught"
const val CONFIRMED_COLUMN            = "confirmed"
const val DESCRIPTION_COLUMN          = "description"
const val DOMESTIC_NAME_COLUMN        = "domestic_name"
const val FIRST_NAME_COLUMN           = "first_name"
const val KEY_COLUMN                  = "key"
const val LAST_NAME_COLUMN            = "last_name"
const val POPULATION_COLUMN           = "population"

const val CRIME_CLASSIFICATION_COLUMN = "classification"
const val CRIME_PERPETRATOR_COLUMN    = "perpetrator"
const val LOCATION_CITY_COLUMN        = "city"
const val LOCATION_COUNTRY_COLUMN     = "country"
const val LOCATION_REGION_COLUMN      = "region"