spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

application:
  name: Covilo
  version: "${version}"

  security:
    key:
      file: covilo.key
      algorithm: Ed25519

    jwt:
      # 40 minutes
      expiration: 2400000
      refresh-token:
        # 22 days
        expiration: 1900800000

  pagination:
    size:
      default: 20
      maximum: 100

  storage:
    avatars: avatars