spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
#        generate_statistics: true
  web:
    resources:
      static-locations: file:run

logging:
  level:
    me.kvdpxne.covilo: trace
    org.springframework.web: debug

covilo:
  allowed-origins:
    - "http://localhost"
    - "http://localhost:4200"
    - "http://localhost:3000"

application:
  storage:
    parent: run/data