application:
  title: "Covilo"
  version: "0.1"
jwt:
  secret: "a0a90d10-d06e-4cc5-9bf9-85910c1575a4"
  experience: 60
logging:
  level:
    org.springframework.security: "debug"
    org.springframework.web: "debug"
spring:
  banner:
    location: banner.txt