spring:
  datasource:
    generate-unique-name: false
    name: postgres-local
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/covilo
    username: postgres
    password: postgres