spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/covilo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off

application:

  name: "Covilo"
  version: "${version}"

  security:
    jwt:
      secret-key: 06pp4fYygg2rayGB1Z47HdjEfTf2qa8A7H7DDZfW0nQnG4nvrE0EVfgP3Jf9aDWa
      expiration: 60000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

covilo:
  allowed-origins:
    - "http://localhost:4200"
