spring:
  datasource:
    generate-unique-name: false
    name: postgres-test-database
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/covilo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  web:
    resources:
      static-locations: file:run

logging:
  level:
    me.kvdpxne.covilo: trace
    org.springframework.web: debug

covilo:
  allowed-origins:
    - "http://localhost"
    - "http://localhost:4200"

application:
  storage:
    parent: run/data