spring:
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

application:
  name: Covilo
  version: ${version}

  security:
    jwt:
      secret-key: 06pp4fYygg2rayGB1Z47HdjEfTf2qa8A7H7DDZfW0nQnG4nvrE0EVfgP3Jf9aDWa
      # 20 minutes
      expiration: 1200000
      refresh-token:
        # 6 hours
        expiration: 21600000

  storage:
    avatars: avatars