spring:
  application:
    name: "Covilo"
    version: "${version}"
  datasource:
    url: jdbc:postgresql://localhost:5432/covilo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

application:

  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

covilo:
  allowed-origins:
    - "http://localhost:4200"
