export * from "./authentication/authentication.component"
export * from "./home/home.component"
export * from "./result-details/result-details.component"
export * from "./result-list/result-list.component"
export * from "./statistics/statistics.component"
